import { StyleSheet } from "react-native";

export const styles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.surfacePage,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    purpleBox: {
      backgroundColor: theme.brandPrimary,
      marginTop: -30,
      marginHorizontal: -30,
      marginBottom: 16,
      paddingVertical: 20,
      paddingHorizontal: 20,
      alignItems: "center",
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
    },
    content: {
      width: "100%",
      maxWidth: 350,
      backgroundColor: theme.surfaceCard,
      borderRadius: 12,
      padding: 30,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
    },
    loadingScreen: {
      flex: 1,
      backgroundColor: theme.surfacePage,
      justifyContent: "center",
      alignItems: "center",
      padding: 24,
    },
    loadingCard: {
      width: "100%",
      maxWidth: 320,
      backgroundColor: theme.brandPrimary,
      borderRadius: 20,
      paddingVertical: 36,
      paddingHorizontal: 24,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 14,
      elevation: 6,
    },
    loadingLogo: {
      width: 240,
      height: 120,
      marginBottom: 24,
    },
    loadingText: {
      marginTop: 16,
      fontSize: 15,
      fontWeight: "600",
      color: theme.textInverse,
      textAlign: "center",
    },
    title: {
      fontSize: 28,
      fontWeight: "bold",
      color: theme.textBody,
      marginBottom: 8,
      textAlign: "center",
    },
    subtitle: {
      fontSize: 14,
      color: theme.textMuted,
      marginTop: 15,
      marginBottom: 15,
      textAlign: "center",
    },
    input: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginBottom: 16,
      fontSize: 14,
      color: theme.textBody,
      backgroundColor: theme.surfaceInput,
    },
    button: {
      backgroundColor: theme.brandPrimary,
      borderRadius: 8,
      paddingVertical: 14,
      marginTop: 8,
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.brandPrimary,
    },
    buttonText: {
      color: theme.textInverse,
      fontSize: 16,
      fontWeight: "600",
      backgroundColor: "transparent",
    },
    changePasswordButton: {
      backgroundColor: "transparent",
      fontSize: 14,
      alignSelf: "center",
    },
    createAccountButton: {
      backgroundColor: "transparent",
    },
    createAccountButtonText: {
      color: theme.brandPrimary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlaySoft,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalContent: {
      width: "100%",
      maxWidth: 350,
      backgroundColor: theme.surfaceCard,
      borderRadius: 12,
      padding: 20,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.textBody,
      textAlign: "center",
      marginBottom: 16,
    },
    closeModalButton: {
      marginTop: 12,
      alignSelf: "center",
    },
    closeModalText: {
      color: theme.brandPrimary,
      fontSize: 14,
      fontWeight: "600",
    },
    footerText: {
      marginTop: 16,
      textAlign: "center",
      fontSize: 12,
      color: theme.textMuted,
    },
    registrationText: {
      marginTop: 16,
      top: 2.5,
      fontSize: 12,
      color: theme.textMuted,
    },
  });

export default styles;
