import { StyleSheet } from "react-native";

export const styles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.surfacePage,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    content: {
      width: "100%",
      maxWidth: 350,
      backgroundColor: theme.surfaceCard,
      borderRadius: 12,
      padding: 30,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
    },
    purpleBox: {
      backgroundColor: theme.brandPrimary,
      marginTop: -30,
      marginHorizontal: -30,
      marginBottom: 16,
      paddingVertical: 20,
      paddingHorizontal: 20,
      alignItems: "center",
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
    },
    title: {
      fontSize: 28,
      fontWeight: "bold",
      color: theme.textBody,
      marginBottom: 8,
      textAlign: "center",
    },
    subtitle: {
      fontSize: 14,
      color: theme.textMuted,
      marginBottom: 24,
      textAlign: "center",
    },
    input: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginBottom: 16,
      fontSize: 14,
      color: theme.textBody,
      backgroundColor: theme.surfaceInput,
    },
    inputsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    halfInput: {
      width: "48%",
    },
    button: {
      backgroundColor: theme.brandPrimary,
      borderRadius: 8,
      paddingVertical: 14,
      marginTop: 8,
      alignItems: "center",
    },
    buttonText: {
      color: theme.textInverse,
      fontSize: 16,
      fontWeight: "600",
      backgroundColor: "transparent",
    },
    registerButton: {
      backgroundColor: "transparent",
      fontSize: 14,
    },
    footerText: {
      marginTop: 16,
      textAlign: "center",
      fontSize: 12,
      color: theme.textMuted,
    },
    registrationText: {
      marginTop: 16,
      top: 2.5,
      fontSize: 12,
      color: theme.textMuted,
    },
    // Stili di un'eventuale modale di conferma, predisposti ma non ancora usati nel JSX.
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlayMedium,
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      width: "90%",
      maxWidth: 350,
      backgroundColor: theme.surfaceCard,
      borderRadius: 12,
      padding: 30,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.textBody,
      marginBottom: 8,
      textAlign: "center",
    },
    modalSubtitle: {
      fontSize: 14,
      color: theme.textMuted,
      marginBottom: 24,
      textAlign: "center",
    },
    modalInput: {
      borderWidth: 1,
      borderColor: theme.borderInput,
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginBottom: 16,
      fontSize: 18,
      color: theme.textBody,
      backgroundColor: theme.surfaceInput,
      textAlign: "center",
      letterSpacing: 2,
    },
    modalButton: {
      backgroundColor: theme.brandPrimary,
      borderRadius: 8,
      paddingVertical: 14,
      marginTop: 8,
      alignItems: "center",
    },
    modalButtonText: {
      color: theme.textInverse,
      fontSize: 16,
      fontWeight: "600",
    },
    modalResendButton: {
      marginTop: 16,
      alignItems: "center",
    },
    modalResendText: {
      color: theme.brandPrimary,
      fontSize: 14,
      textDecorationLine: "underline",
    },
    modalCloseButton: {
      marginTop: 12,
      alignItems: "center",
    },
    modalCloseText: {
      color: theme.textMuted,
      fontSize: 14,
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 10,
      marginTop: 14,
    },
    modalActionButton: {
      flex: 1,
    },
    monthControls: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    monthArrowButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.surfaceAccent,
      alignItems: "center",
      justifyContent: "center",
    },
    monthArrowButtonDisabled: {
      opacity: 0.35,
    },
    monthArrowText: {
      color: theme.brandPrimary,
      fontSize: 20,
      fontWeight: "700",
      lineHeight: 22,
    },
    monthValueText: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.textPrimary,
      minWidth: 50,
      textAlign: "center",
    },
    yearControls: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    yearArrowButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.surfaceAccent,
      alignItems: "center",
      justifyContent: "center",
    },
    yearArrowButtonDisabled: {
      opacity: 0.35,
    },
    yearArrowText: {
      color: theme.brandPrimary,
      fontSize: 20,
      fontWeight: "700",
      lineHeight: 22,
    },
    yearValueText: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.textPrimary,
    },
  });

export default styles;
